### ISSUE TITLE
convert electrode boilerplate features list to a link or list 

### ISSUE THREAD

**Issue by ananavati** [electrode-io/electrode-io.github.io#115]
React * Redux * CSS Modules * Electrode-Server * Electrode Confippet * Universal JavaScript Babel * Webapack * Webpack Isomorphic Loader * React-Router * History React-Resolver * Electrode Bundle Analyzer Electrode-Static-Paths * Lodash * Electrode-Docgen * Bluebird * Gulp * ESLint * Mocha * Enzyme * Travis * Yeoman

**Comment by tiffine-koch** [comment]
Created a list format of the above with a link to "Getting Started: What's Inside" for further reading:
![screen shot 2016-09-20 at 10 24 11 am](https://cloud.githubusercontent.com/assets/13398279/18683606/c3019334-7f25-11e6-8268-10c191e70477.png)
