### ISSUE TITLE
Heroku Deploy App page - missing step

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#116]
When following [deploy-app](https://electrode-io.github.io/docs/deploy_app.html) instructions to the letter, when I run `heroku open` the app fails to launch in the browser (I see an Application Error screen).  

Found out that the origin of the error is due to a missing step in the documentation page. 
After adding the engine section (for node 4.2.x) in package.json, the change needs to be comitted to git (otherwise it does not get pushed to heroku when running `git push heroku master`, and heroku install a wrong node version).

After `It should now look like this` (and before `Create an app on Heroku` (which prepares Heroku to receive your source code) you should add something along the line of :

--
You should now commit your changes

`$ git add .`
`$ git commit -m "Update package.json"`

**Comment by tiffine-koch** [comment]
Added missing steps, thanks @belemaire
