### ISSUE TITLE
Heroku Deploy App page - Incoherency with Procfile

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#117]
At the end of the [deploy-app](https://electrode-io.github.io/docs/deploy_app.html) documentation page, it is said to create a `Procfile` text file and add some code into it.  

However, `Profile` is part of `.gitignore`, so when running `git push heroku master`, nothing new will be pushed (the `Procfile` file won't be). 

If this step needs to be done, `Procfile` should be removed from `.gitignore` and two steps should be added before `git push heroku master` : `git add .` and `git commit -m "Add Procfile"`.

If this step does not need to be done, then it should be removed from the doc.

**Comment by tiffine-koch** [comment]
Removed Procfile reference + steps after talking further with @caoyangs. This was an unnecessary step.
