### ISSUE TITLE
What's Inside page remarks

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#118]
#Some remarks for [What's Inside](https://electrode-io.github.io/docs/whats_inside.html) page :

**Wrongly formatted text**

Found out a lot of entries referring to files, that seems to be wrongly formatted. For example
<your-awesome-app'>/client/styles/base.css:

I think it should be `<your-awesome-app>/client/styles/base.css` instead

Search for <your-awesome-app'> in the page to find all of them.

**Wrong link**

At the end of the page it links to `Intermediate: Create a Standalone Component`. However this page does not exist in the doc. It should rather be `Intermediate: Create a Reusable Component`.

**Comment by tiffine-koch** [comment]
Resolved issue in merged PR #123
