### ISSUE TITLE
Create a Reusable Component page issue

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#119]
When following instructions in [Create a Reusable Component](https://electrode-io.github.io/docs/create_reusable_component.html) page, I get an error at some point when running `gulp check` command part of [Develop Tests section](https://electrode-io.github.io/docs/create_reusable_component.html#develop-tests-for-the-above-components) .

The linter fails to invalidly formatted file `home.jsx` created previously by copy/pasting it from [Build Component](https://electrode-io.github.io/docs/build_component.html) page.

Here are the linter errors :

```
/Users/blemair/Code/my-electrode-app/client/components/home.jsx
   4:3   error  Strings must use doublequote                         quotes
   5:3   error  Strings must use doublequote                         quotes
   6:3   error  Strings must use doublequote                         quotes
   7:3   error  Strings must use doublequote                         quotes
   8:1   error  Line 8 exceeds the maximum line length of 100        max-len
   8:3   error  Strings must use doublequote                         quotes
  11:8   error  Unexpected var, use let or const instead             no-var
  11:13  error  Infix operators must be spaced                       space-infix-ops
  14:25  error  "i" is already declared in the upper scope           no-shadow
  25:26  error  Expected parentheses around arrow function argument  arrow-parens
```

File `home.jsx` in [Build Component](https://electrode-io.github.io/docs/build_component.html) needs to be edited accordingly to remove all linter errors.

**Comment by jamesmcintyre** [comment]
@raydecastro @ananavati I'm taking care of this, sorry for the miscommunication but I was already working on fixing these!

**Comment by tiffine-koch** [comment]
@jamesmcintyre @ananavati This the PR James has to fix these errors: https://github.com/docs-code-examples-electrode-io/electrode-houseparty-example-component/pull/4

**Comment by ananavati** [comment]
fixed in pr https://github.com/docs-code-examples-electrode-io/electrode-houseparty-example-component/pull/4
