### ISSUE TITLE
Create a Reusable Component > Add Data [remarks]

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#124]
The third code box in [Add Data](https://electrode-io.github.io/docs/add_data.html) is kind of confusing.

The text say `Add the code below between your components tags:` and in the code box it says `-insert code below here`. What is the code to insert ?

The next code block and last one show the final code.

I don't see a reason for the third code box, I think you should just tell user to replace the code by copy/pasting the whole code from the 4th code block. It it more coherent with previous doc pages as well.

Should not forget to mention to replace `YourAwesomeComponent` with whatever name the user used to create the component previously (as mentioned in previous doc pages)

**Comment by tiffine-koch** [comment]
Resolved in pr #136
