### ISSUE TITLE
Gulp tasks missing ?

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#125]
In [Build and Demo](https://electrode-io.github.io/docs/build_and_demo.html) page, when running command `gulp build && gulp demo` I get an error saying `Task 'demo' is not in your gulp file`. 

Looking at my project `gulpfile.js`, I can see `require("electrode-archetype-react-app")();`. Looking at my local `electrode-archetype-react-app` module (`v1.2.0`), I can see indeed that no `demo` task is present in `arch-gulpfile.js` file.

Same problem in [Generate Docs](https://electrode-io.github.io/docs/generate_docs.html).  
`generate-metadata` `generate-documentation` and `generate` are non defined gulp tasks

**Comment by ananavati** [comment]
for build & demo step, its building a electrode-component 
so the `demo` will be in the `component/gulpfile.js` generated as part of `yo electrode-component`

https://github.com/electrode-io/generator-electrode-component/blob/master/app/templates/_gulpfile.js#L16

**Comment by belemaire** [comment]
@ananavati : :+1: I can see all of the gulp tasks in the component gulp file indeed.

The command has to be run from within the component folder (this should be explicitly mentioned in the documentation, because in all previous instructions pages we were working from the root electrode app folder).

**Comment by ananavati** [comment]
fixed in pr https://github.com/electrode-io/electrode-io.github.io/pull/134
