### ISSUE TITLE
Build and demo page : Add instruction

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#127]
On the [Build and Demo](https://electrode-io.github.io/docs/build_and_demo.html) page, running `gulp build && gulp demo` does not automatically open a browser to show the demo.

It should be mentioned that after running this command line, the user should navigate to `http://localhost:4000` in a browser to see the demo running.

**Comment by tiffine-koch** [comment]
Resolved in pr #136
