### ISSUE TITLE
Add Routes : Couple confusing points

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#129]
Few confusing stuff in the In the [Add Routes](https://electrode-io.github.io/docs/add_routes.html) page :

- I don't understand why I would need to install my component as a node module .. It is already there in my application folder. Is that really needed ? Or can I continue working with my previously created component directly (if so this whole npm install part should be removed from doc).

- I think there is a typo just below the first code box (`Navigate to <your-awesome-component>/client/routes.jsx.`), should it rather read  `Navigate to <your-awesome-app>/client/routes.jsx.` (as there is no client folder in my component folder).

- `Change from the literal YourAwesomeComponent to your actual component name:` >>> this mention is not needed as there is no `YourAwesomeComponent` reference in code from this page,

**Comment by belemaire** [comment]
For first point, I think the code box (and associated comment) should not react `npm i your-awesome-npm-module --save` but rather `npm i electrode-houseparty-example-component` . See https://github.com/electrode-io/electrode-io.github.io/issues/135 for more info (related issues)

**Comment by tiffine-koch** [comment]
Resolved in PR #144 by using clear call outs of where the user is supposed to be (app vs. component) and directions on generating yo electrode-component in a new directory.
