### ISSUE TITLE
Server Config : gulp hot need github OAUTH2 token

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#137]
Running `gulp hot` fails because OAUTH2 token is not found.

In [Build a Server Plugin](https://electrode-io.github.io/docs/build_server_plugin.html) page, there is a quick reference to setting token locally `token='your-token-here'` but not mentioned when actually useful.

`gulp hot` command should indeed be `token='your-token-here' gulp hot` to run gulp hot while providing it the token (or set the token in another manner ... whatever is best)

**Comment by tiffine-koch** [comment]
I think the oAuth initial description should stay in Build a Server Plugin because this is where we ask the user to generate the token and give the context + code of why we need it. I added it where you suggested and prefaced that we would be using it again.
