### ISSUE TITLE
Stand Alone Modules > Confippet - clarification

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#141]
[Confippet](https://electrode-io.github.io/docs/confippet.html).

 I find the `Getting Started` section a bit confusing. Whereas in all of the previous sections we were actually building a project and trying out stuff for real, guided by steps by steps instructions, this page here is more to demonstrate the usage of Confippet but not to really guide user through steps by steps instructions inside a previously created app.

This is a bit confusing because in this getting started the verbs tense used denote an action that the user should take while reading the doc, as in previous sections. i.e `we'll create two config files` .. `Create config/ directory by running mkdir config` ...

This page seems not to be instructions for the user to take to try it out, but seems more to be a demonstration / sample usage. 

Maybe `Getting Started / Basic Use` could be renamed to `Example Basic Use` and describe more of a scenario that Confipett can be used for (instead of instructions that are intended to the user to do) ... something along the lines of: 

`Example Usage Scenario`

Let's say that in our application we need to access a database that is running locally in our development environment but is running on a specific hostname while running in our production environment. We would like to be able to get the correct hostname in our code, without too much effort, based on the current environment.
Confippet can help us with this. All we have to do is to create a config/ directory inside our main app directory and ....

Hope this makes sense.

**Comment by raydecastro** [comment]
Issue fixed by https://github.com/electrode-io/electrode-io.github.io/pull/145

**Comment by AlexG92** [comment]
Can we please note down that these are just examples and we are not going to be walking through stuff with them? (Until we do :) )?

**Comment by raydecastro** [comment]
I'm not sure what text exactly to add here. The original text of the getting started section came from the confippet [readme](https://github.com/electrode-io/electrode-confippet#getting-started) file. On the last paragraph, it does state that it's an example: "In this example, default.json will be loaded in all environments, ..."

**Comment by georgeweiler** [comment]
Issue fixed by #344
