### ISSUE TITLE
Confippet : Extend usage scope

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-io.github.io#142]
In [Confippet](https://electrode-io.github.io/docs/confippet.html) page 

These two lines somehow restrict the usage scope of Confippet to web server framework based node.js apps :

- `Confippet can be used as a standalone module in your favorite node.js web server framework.`
- `Platform Agnostic - This module is platform agnostic and can be plugged-in Electrode, Express.js and Hapi.js applications.`

Howver in [Stand Alone Modules](https://electrode-io.github.io/docs/stand_alone_modules.html) page, it is stated `Confippet is a versatile, flexible utility for managing configurations of Node.js applications.`, as well as in the [Confipett repo](https://github.com/electrode-io/electrode-confippet) itself.

These two lines should rather read :

- `Confippet can be used as a standalone module in your favorite Node.js web server framework or application.`
- `Platform Agnostic - This module is platform agnostic and can be plugged-in Electrode, Express.js and Hapi.js applications or any Node.js application.`

**Comment by raydecastro** [comment]
Issue fixed by: https://github.com/electrode-io/electrode-io.github.io/pull/145

**Comment by tiffine-koch** [comment]
@raydecastro resolves this in merged PR #145
