### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#149]
in our faq, we should put..

why do we focus on universal js?

is electrode really being used to power walmart?

**Comment by tiffine-koch** [comment]
I'll save this started FAQ page skeleton, but we will update from "Coming Soon" version once we have a list of questions 
<img width="611" alt="screen shot 2016-09-21 at 1 10 56 pm" src="https://cloud.githubusercontent.com/assets/13398279/18727329/ff13fac4-7ffc-11e6-8160-a0cf2e344854.png">

**Comment by caoyangs** [comment]
https://github.com/electrode-io/electrode-io.github.io/issues/166

Q: Why is my server throwing error "cannot find module ..." on start up?

A: Most likely you are using npm@2. Upgrade to npm@3 by running command `npm i -g npm@3` and redo `npm i`.

**Comment by ananavati** [comment]
https://github.com/electrode-io/electrode-io.github.io/blob/develop/_docs/05.4-faq.markdown
