### ISSUE TITLE
In Yeoman, electrode (which is the generator-electrode) doesn't go directly to correct repo

### ISSUE THREAD

**Issue by tiffine-koch** [electrode-io/electrode-io.github.io#151]
It redirects to entire electrode org in GitHub instead of the generator-electrode repo (https://github.com/electrode-io/generator-electrode)
<img width="1175" alt="screen shot 2016-09-21 at 11 04 01 am" src="https://cloud.githubusercontent.com/assets/13398279/18722939/7a93f6b6-7feb-11e6-8200-8b27da5e82c3.png">

**Comment by raydecastro** [comment]
I think this issue should go to the generator-electrode repo instead.

**Comment by raydecastro** [comment]
I think it should be an easy fix, just updating this field probably: 
"homepage": "https://github.com/electrode-io/generator-electrode",
in package.json + publishing it.

**Comment by ananavati** [comment]
@raydecastro can you please pr into `generator-electrode` repo.

**Comment by raydecastro** [comment]
@ananavati will do.
