### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by caoyangs** [electrode-io/electrode-io.github.io#156]
https://github.com/electrode-io/electrode-io.github.io/blob/develop/_docs/03.1-create_reusable_component.markdown

Let's begin by creating using `cd` to exit Your-Awesome-App and return to our root to create a new directory:

```bash
$ cd
$ mkdir my-electrode-component
$ cd my-electrode-component
```

Also the first `cd` should probably be `cd ..`

**Comment by tiffine-koch** [comment]
Resolved with pr #159
