### ISSUE TITLE
Add Examples?

### ISSUE THREAD

**Issue by caoyangs** [electrode-io/electrode-io.github.io#158]
https://github.com/electrode-io/electrode-io.github.io/blob/develop/_docs/03.1.6-add_data.markdown

Should this be renamed to `add_examples`?

**Comment by tiffine-koch** [comment]
I agree and think this is more clear. And change the subheading to "Add Examples to Your Demo."

**Comment by ananavati** [comment]
👍

**Comment by tiffine-koch** [comment]
Resolved by pr #162
