### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by Wei-Zou** [electrode-io/electrode-io.github.io#166]
`yo electrode` ends up with error 
```Error: Cannot find module 'lodash'```
Did it assume lodash as global module?

**Comment by Wei-Zou** [comment]
Not valid. npm version was 2.x.x. Didn't see the error when running `sudo npm install -g yo gulp generator-electrode`. Maybe put in FAQ session.

**Comment by AlexG92** [comment]
Let's note this as a warning or something in our logging.

and our FAQ.
