### ISSUE TITLE
Missing page of yo electrode vs boilerplate

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#204]

**Comment by ananavati** [comment]
moving this as part of faq's ` What is the difference between creating a new electrode app using yo electrode vs cloning/forking Electrode Boilerplate?`

**Comment by ananavati** [comment]
https://github.com/electrode-io/electrode-io.github.io/blob/develop/_docs/05.4-faq.markdown#4-what-is-the-difference-between-creating-a-new-electrode-app-using-yo-electrode-vs-cloningforking-electrode-boilerplate
