### ISSUE TITLE
Inconsitent: sample project name

### ISSUE THREAD

**Issue by jspears** [electrode-io/electrode-io.github.io#211]
It should have one name used everywhere, makes it easier to follow and understand what is going on as they complete the parts..  

my-electrode-component
in some it says
(Develop Styles)
your-awesome-component.css
(Add Routes)
your-awesome-published-npm-module
(Server Config)
your-awesome-app

**Comment by ananavati** [comment]
fixed in pr https://github.com/electrode-io/electrode-io.github.io/pull/342
