### ISSUE TITLE
electrode docs has a JS error

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#225]
vqa1hcx.js:53 Typekit: the domain "www.electrode.io" isn't in the list of published domains for kit "vqa1hcx".rb.load @ vqa1hcx.js:53Fa @ vqa1hcx.js:34Da.load @ vqa1hcx.js:33window.Typekit.load @ vqa1hcx.js:57(anonymous function) @ what_is_electrode.html:25

**Comment by raydecastro** [comment]
@AlexG92 I think this may have already been fixed. I'm not seeing that error now.

**Comment by tiffine-koch** [comment]
@raydecastro I removed the console.error so the user wouldn't receive it, but this still needs to be fixed: 
Line 26 of default.html, we removed the message to users in pr 283:
line 26: `  <script>try{Typekit.load();}catch(e){}</script>`

I found this online: https://helpx.adobe.com/typekit/kb/troubleshoot-adding-fonts-website.html

**Comment by ananavati** [comment]
fix was deployed.
