### ISSUE TITLE
Electrode is by default SSR

### ISSUE THREAD

**Issue by mdeverkonda** [electrode-io/electrode-io.github.io#23]
We need to callout that electrode by default is SSR.

**Comment by tiffine-koch** [comment]
We called this out in the Features section of What is Electrodew with a link about Universal Javascript:
![screen shot 2016-09-19 at 9 49 41 am](https://cloud.githubusercontent.com/assets/13398279/18640783/754c98f0-7e4e-11e6-945a-606755beff21.png)
