### ISSUE TITLE
Can "ELECTRODE CORE" be rewritten?

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#245]
@NicholasDunham: now that you have more context, can you please help write the content of Electrode Core... @ananavati : can you help with the pitch on that?

Get new projects started quickly with a simple, consistent structure that follows modern best practices. Electrode Core allows you to build a flexible scaffold in minutes, with support for server-side rendering and easy deployment to multiple cloud providers.

The heart of the platform is Electrode Archetypes, which allow for standardized configurations and structure of the app and its associated react components. By enforcing a sensible structure and consistency for components, modules and the entire app, Electrode’s Archetype system helps you build scalable applications you can trust while ensuring streamlined development and deployment.

**Comment by ananavati** [comment]
https://github.com/electrode-io/electrode-io.github.io/blob/e8102065386c905b1e260c16248b1c252b3b4c77/_docs/01.1-what_is_electrode.markdown#core-quick--easy
