### ISSUE TITLE
Home page explorer graphic problems

### ISSUE THREAD

**Issue by jherr** [electrode-io/electrode-io.github.io#255]
On the home page the image of the explorer on the mac has several problems:

* The demo section is not reflecting what's in the editor above it.
* The usage line points to just the "hide usage" button where it should bracket that section. Same with dependencies.
* "Documents" should be "Documentation"
* "Code" should be "Live Code Preview", or something like that.

**Comment by caoyangs** [comment]
Which page are you talking about exactly? A link would help.
