### ISSUE TITLE
Clarify the reusability in Reusable Electrode Components

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#295]
Can we explain that our reusable components are for reusing across different apps, so they are made for being developed independently, then consumed via explorer, so they take extra space to be able to develop independently, and if you just have one app, they probably shouldn't follow this model

**Comment by ananavati** [comment]
https://github.com/electrode-io/electrode-io.github.io/blob/develop/_docs/05.4-faq.markdown#5-what-do-you-mean-by-reusable-electrode-components

pending deploy to PROD
