### ISSUE TITLE
"What's Inside" references "History" module that is not present in real code

### ISSUE THREAD

**Issue by ezralalonde** [electrode-io/electrode-io.github.io#298]
The `history` module referenced on electrode-io.github.io/_docs/02.6-whats_inside.markdown is not actually a part of your project, if you follow the other steps. 

* [Path to file](https://github.com/electrode-io/electrode-io.github.io/blob/develop/_docs/02.6-whats_inside.markdown)
* [As it appears online](http://www.electrode.io/docs/whats_inside.html)
* [The contents of the app.jsx file](https://github.com/electrode-io/generator-electrode/blob/master/generators/app/templates/client/app.jsx)

We can remove all references to the module from the "What's Inside" page.

1) ` import { createHistory } from "history";`
2) `      () => <Router history={createHistory()}>{routes}</Router>,`
3) Explanation of what `history` is/does.

It appears that [`generator-electrode` was updated](https://github.com/electrode-io/generator-electrode/commit/21fa9704c4f3126243a81a6e9669df29af64740d) without the docs changing.

**Comment by aaroncalderon** [comment]
I just ran `npm install --save history` on my project root and that fixed the issue. Instead, we could update generator-electrode to include `history` by default.
