### ISSUE TITLE
Quick Start Suggestion

### ISSUE THREAD

**Issue by aarmand** [electrode-io/electrode-io.github.io#305]
The quickstart goes through a series of processes that seem to me are already done in the yo generator process. Examples: git init is already done which causes errors when you try to follow the  heroku install instructions. When you run 'git init' it re-initializes. When you run 'git add origin' the origin already exists.

Also, "heroku build" script is already in the json package so you dont have to add it.

Just a UX FYI. 

Thanks.

**Comment by caoyangs** [comment]
@aarmand Thanks for checking out electrode

As far as I can tell, `git init` is not done in the yo generator process, and origin does not exist before you run `git add origin`. Unless you already checked out a git repo before doing `yo electrode`?

We will remove the `heroku build` step from the doc.
