### ISSUE TITLE
Intermediate walk through assumes Phantomjs install?

### ISSUE THREAD

**Issue by masonhensley** [electrode-io/electrode-io.github.io#312]
On this page: http://www.electrode.io/docs/test_components.html

Code=> https://github.com/electrode-io/electrode-io.github.io/blob/develop/_docs/03.1.5-test_components.markdown

`gulp check` command fails as shown below. Manually installating of phantomjs by `npm install phantomjs` fixed the specific gulp task (test-frontend-cov) that was failing on my local machine.

```
$ gulp test-frontend-cov
[13:36:06] Using gulpfile ~/code/electrode/gulpfile.js
[13:36:06] Starting 'test-frontend-cov'...
10 10 2016 13:36:14.416:INFO [karma]: Karma v0.13.22 server started at http://localhost:8080/
10 10 2016 13:36:14.422:INFO [launcher]: Starting browser PhantomJS
10 10 2016 13:36:14.622:ERROR [launcher]: Cannot start PhantomJS

10 10 2016 13:36:14.628:INFO [launcher]: Trying to start PhantomJS again (1/2).
10 10 2016 13:36:14.730:ERROR [launcher]: Cannot start PhantomJS

10 10 2016 13:36:14.731:INFO [launcher]: Trying to start PhantomJS again (2/2).
10 10 2016 13:36:14.832:ERROR [launcher]: Cannot start PhantomJS

10 10 2016 13:36:14.834:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
```

Not sure how or if y'all would prefer to remedy this, and I can create a PR with a little direction.  Thanks for the library!

**Comment by ananavati** [comment]
@masonhensley can you please send the `node -v` and the `npm -v` versions your are running on?

**Comment by masonhensley** [comment]
Sorry for the delay.

```
node -v
v6.1.0

npm -v
3.10.8

**Comment by ananavati** [comment]
fix in pr: https://github.com/electrode-io/electrode-archetype-react-app/pull/34

**Comment by ananavati** [comment]
published 
```+ electrode-archetype-react-app@1.3.3
+ electrode-archetype-react-app-dev@1.3.3```

@masonhensley can you please try out with the patch release of `electrode-archetype-react-app`  and close this bug if your issue is resolved

**Comment by ananavati** [comment]
<img width="881" alt="screen shot 2016-11-17 at 9 38 03 am" src="https://cloud.githubusercontent.com/assets/360041/20400485/b1ce6270-aca9-11e6-9bde-d65709c407fb.png">
