### ISSUE TITLE
Reusable Component - Styles missing

### ISSUE THREAD

**Issue by LeeFrancis** [electrode-io/electrode-io.github.io#341]
I am creating a reusable component as per http://www.electrode.io/docs/create_reusable_component.html and I publish it to npm.
I take all the defaults for :
`  yo electrode-component
`
In another project I include this as a dependency.
The example wysiwyg-component is missing styles under the lib directory so my build fails.

What am I missing?

    Module not found: Error: Cannot resolve 'file' or 'directory' ../styles/wysiwyg-component.css in /Users/xxxx/testproj/node_modules/@xxxxx/wysiwyg-component/lib/components
     @ ./~/@xxxx/wysiwyg-component/lib/components/wysiwyg-component.js

**Comment by ananavati** [comment]
fixed in pr https://github.com/electrode-io/generator-electrode-component/pull/16

**Comment by ananavati** [comment]
duplicate issue https://github.com/electrode-io/electrode-io.github.io/issues/312

**Comment by ananavati** [comment]
fix published in `+ generator-electrode-component@1.2.0` 

@LeeFrancis can we please close out the issue if this version update fixes your issue.

**Comment by LeeFrancis** [comment]
Thank you..
