### ISSUE TITLE
Intermediate => Create a Reusable Component => Component Helper documentation

### ISSUE THREAD

**Issue by alecwhittington** [electrode-io/electrode-io.github.io#356]
First off great OSS project. We are bringing Electrode into our company and I am working through the docs and getting our core pieces setup. 

When reviewing the documentation, I found the Component Helper example to be lacking in its usage as well as documenting the purpose of component helpers in general (with in the Electrode ecosystem).

It would probably be a good idea to to add:
- Better documentation as to the purpose of components helpers
- An example of the component helper being used within the Create a Reusable Component sample project

Thank you for providing Electrode to the community. If someone wanted to explain the points above, I'd be more than happy to update the documentation and provide a pull request

**Comment by alecwhittington** [comment]
Found the usage of the helper on [low level components](http://www.electrode.io/docs/low_level_components.html) inside the render-friend.jsx component

**Comment by ananavati** [comment]
> First off great OSS project
> Thank you for providing Electrode to the community. 

thanks for the kind words @alecwhittington and I am glad Electrode is being considered inside your company as a solve.

> re: When reviewing the documentation, I found the Component Helper example to be lacking in its usage as well as documenting the purpose of component helpers in general (with in the Electrode ecosystem).

the component helper example here http://www.electrode.io/docs/component_helpers.html is custom and specific to the example demo component that we are building as part of the docs, its basically a few utilities/helper code to render the `guest list component` as part of the demo exercise, but yes we are available and willing to add additional docs and provide more clarity on the usage of the helper component.
