### ISSUE TITLE
Too GitHub Specific, should allow for other Git providers

### ISSUE THREAD

**Issue by alecwhittington** [electrode-io/electrode-io.github.io#357]
While I myself am a GitHub fan, my company is heavily invested in BitBucket (and Atlassian in general). 

All of the generators as well as the Electrode Explorer are GitHub specific. While the generators do nothing more than add these items to the package.json, Electrode Explorer is tied very heavily to GitHub. 

It would be a nice feature to be able to select GitHub or BitBucket (any git Provider that provides a API hook really) when using a generator or setting up the Electrode Explorer.

**Comment by ananavati** [comment]
@alecwhittington 

great suggestion on making generator & explorer agnostic of git hosting provider! added a feature request to our backlog of features. https://github.com/electrode-io/electrode-explorer/issues/9
