### ISSUE TITLE
More clarity needed in 'Above the folder server render' section

### ISSUE THREAD

**Issue by mdeverkonda** [electrode-io/electrode-io.github.io#70]
Below statement in the usage section of 'Above the folder server render' is not very clear.
'By default, the above-the-fold-only-server-render component is an exercise in simplicity; high-level it returns the child component.'

**Comment by ananavati** [comment]
hopeful fix in commit: https://github.com/electrode-io/electrode-io.github.io/commit/38b090cd017957694a9c90dd3674473f73a8e8e5
