### ISSUE TITLE
add a page for distinction between what you get from yo electrode vs cloning electrode-boilerplate

### ISSUE THREAD

**Issue by ananavati** [electrode-io/electrode-io.github.io#76]

**Comment by tiffine-koch** [comment]
I'm taking this one.

**Comment by tiffine-koch** [comment]
Submitted PR for this issue:
<img width="647" alt="screen shot 2016-09-19 at 4 10 37 pm" src="https://cloud.githubusercontent.com/assets/13398279/18652045/1e54523c-7e84-11e6-955f-7042783abfd7.png">

**Comment by tiffine-koch** [comment]
Fixed in pr: https://github.com/electrode-io/electrode-io.github.io/pull/110
