### ISSUE TITLE
01.4 Requirements

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#79]
We have two paragraphs for requirements, instead of a list or something shorter?

**Comment by tiffine-koch** [comment]
Updated as a shorter paragraph w/ a list. Submitting a PR for review:
![screen shot 2016-09-19 at 10 08 06 am](https://cloud.githubusercontent.com/assets/13398279/18641340/10e5887e-7e51-11e6-8978-87cdbf337098.png)

**Comment by tiffine-koch** [comment]
Updated as a shorter paragraph w/ a list. Submitting a PR for review:
![screen shot 2016-09-19 at 10 10 05 am](https://cloud.githubusercontent.com/assets/13398279/18641404/4bd71bd2-7e51-11e6-9cb3-d9397b10f5d9.png)

**Comment by tiffine-koch** [comment]
Updated as a shorter paragraph w/ a list. Submitting a PR for review:
![screen shot 2016-09-19 at 10 08 06 am](https://cloud.githubusercontent.com/assets/13398279/18641412/59edc8ec-7e51-11e6-80a6-8a550648aee0.png)

**Comment by tiffine-koch** [comment]
Updated as a shorter paragraph w/ a list. Submitting a PR for review:
![screen shot 2016-09-19 at 10 11 32 am](https://cloud.githubusercontent.com/assets/13398279/18641438/76ed0cd2-7e51-11e6-891c-c2595a9a9158.png)

**Comment by tiffine-koch** [comment]
Updated order of requirements per @ananavati:
![screen shot 2016-09-19 at 11 47 57 am](https://cloud.githubusercontent.com/assets/13398279/18644647/076f5320-7e5f-11e6-8882-5ade45a67556.png)
