### ISSUE TITLE
why do we create reusable component?

### ISSUE THREAD

**Issue by ananavati** [electrode-io/electrode-io.github.io#86]

**Comment by alexanthony813** [comment]
I'm taking this one. 

__________________
Building this application with React components will allow for greater modularity, which will enable reuse of code in later iterations. This Service-oriented Architecture also greatly increases workflow efficiency by allowing developers to easily divide and conquer tasks during the production process. Furthermore, better separation of concerns allows for much easier debugging in general.

**Comment by ananavati** [comment]
closing this and combining into https://github.com/electrode-io/electrode-io.github.io/issues/87
