### ISSUE TITLE
For reusable component

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#87]
- we need to explain why its abstracted and standalone
- We should break it into sub nav steps

**Comment by alexanthony813** [comment]
I'm taking this one.

**Comment by alexanthony813** [comment]
Done, waiting for prior PR to be merged before I push changes and do new PR.

**Comment by alexanthony813** [comment]
This has been reviewed and merged.

**Comment by alexanthony813** [comment]
This has been reviewed and merged.
