### ISSUE TITLE
fix links and titles of advanced standalone modules.

### ISSUE THREAD

**Issue by ananavati** [electrode-io/electrode-io.github.io#89]

**Comment by raydecastro** [comment]
In progress.

**Comment by raydecastro** [comment]
as per @tiffine-koch, we will make the sample apps link to the actual fragment of the section of the specified module in the sample app's readme. cc: @ananavati

**Comment by raydecastro** [comment]
Titles and links have been fixed. There should be 4 PRs to resolve this issue.

**Comment by raydecastro** [comment]
https://github.com/electrode-io/electrode-io.github.io/pull/108 
https://github.com/electrode-io/electrode-boilerplate-universal-react-node/pull/22 
https://github.com/docs-code-examples-electrode-io/hapi-react-redux/pull/6 
https://github.com/docs-code-examples-electrode-io/express-react-redux-webpack/pull/5
